### ISSUE TITLE
Migrating from pkcs11wrapper

### ISSUE THREAD

**Issue by MrWildanMD** [xipki/ipkcs11wrapper#5]
what is the equivalent of these?
```java
// import iaik.pkcs.pkcs11.objects.*;
// import iaik.pkcs.pkcs11.wrapper.PKCS11Constants;
// import iaik.pkcs.pkcs11.*;
// import iaik.pkcs.pkcs11.Mechanism;
// import iaik.pkcs.pkcs11.Module;
// import iaik.pkcs.pkcs11.parameters.InitializationVectorParameters;
```
because the pkcs11wrapper throw error:
```
[*] Registering PKCS#11 Module
Exception in thread "main" java.lang.IllegalAccessError: class iaik.pkcs.pkcs11.Module (in unnamed module @0x2b48a640) cannot access class sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS (in module jdk.crypto.cryptoki) because module jdk.crypto.cryptoki does not export sun.security.pkcs11.wrapper to unnamed module @0x2b48a640
        at iaik.pkcs.pkcs11.Module.initialize(Module.java:271)
        at com.willmd.pki.Pkcs11PrivateWrapper.registerModule(Pkcs11PrivateWrapper.java:88)
        at com.willmd.pki.Pkcs11PrivateWrapper.main(Pkcs11PrivateWrapper.java:31)
        
```

**Comment by xipki** [comment]
Do you use ipkcs11wrapper or jpkcs11wrapper? The error message indicates jpkcs11wrapper.

**Comment by MrWildanMD** [comment]
Alright it fixed because my maven used java 17 instead java 8
